package com.turboquant.ai.engine

import android.util.Log
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.channelFlow
import kotlinx.coroutines.flow.flow
import kotlinx.coroutines.flow.flowOn
import kotlinx.coroutines.sync.Mutex
import kotlinx.coroutines.sync.withLock
import java.io.File

private const val TAG = "InferenceManager"

// Developer-defined context window for Gemma 2B
private const val GEMMA_N_CTX = 2048

/** Represents a single turn in the conversation. */
data class ChatMessage(
    val role: MessageRole,
    val content: String
)

enum class MessageRole { USER, ASSISTANT }

/** Emitted by [InferenceManager.generate] for each streamed piece. */
sealed class InferenceToken {
    /** A text piece generated by the model. */
    data class Piece(val text: String) : InferenceToken()

    /** Generation finished normally. */
    object Done : InferenceToken()

    /** Fatal inference error. */
    data class Error(val message: String) : InferenceToken()
}

/**
 * Manages the full inference lifecycle:
 *  - Model loading (one-time, cached in memory)
 *  - Multi-turn conversation context (incremental KV cache)
 *  - Token streaming via Kotlin [Flow]
 *  - Thread-safe access via [Mutex]
 *
 * The Gemma 2B chat template used here:
 * ```
 * <bos><start_of_turn>user\n{msg1}<end_of_turn>\n
 * <start_of_turn>model\n{resp1}<end_of_turn>\n
 * <start_of_turn>user\n{msg2}<end_of_turn>\n
 * <start_of_turn>model\n
 * ```
 * The BOS token is prepended only on Turn 1 (via llama_tokenize add_special=true on
 * the full formatted conversation). From Turn 2 onwards, Kotlin appends to the
 * existing KV cache (the bridge does NOT re-add BOS because the context carries
 * the state from the previous turn).
 */
class InferenceManager(private val engine: TurboQuantEngine) {

    private val mutex = Mutex()

    // Opaque native pointers (0 = not initialized)
    private var modelPtr: Long = 0L
    private var ctxPtr:   Long = 0L

    // Conversation history maintained on the Kotlin side
    private val history = mutableListOf<ChatMessage>()

    // Track whether the first prompt has been decoded (for BOS handling)
    private var sessionStarted = false

    // ── Model initialization ──────────────────────────────────────────────

    /**
     * Load the model and create the inference context.
     * Safe to call from a coroutine (runs on [Dispatchers.IO]).
     * Throws if the model file doesn't exist.
     */
    suspend fun initialize(modelFile: File) {
        mutex.withLock {
            if (ctxPtr != 0L) {
                Log.i(TAG, "Model already loaded")
                return
            }
            require(modelFile.exists()) {
                "Model file not found: ${modelFile.absolutePath}"
            }

            Log.i(TAG, "Initializing TurboQuant engine, model=${modelFile.name}")
            engine.nativeBackendInit()

            modelPtr = engine.nativeLoadModel(modelFile.absolutePath)
            if (modelPtr == 0L) throw RuntimeException("Failed to load model")

            ctxPtr = engine.nativeCreateContext(modelPtr, GEMMA_N_CTX)
            if (ctxPtr == 0L) throw RuntimeException("Failed to create inference context")

            sessionStarted = false
            history.clear()
            Log.i(TAG, "Engine initialized — n_ctx=$GEMMA_N_CTX, KV type=TQ2_0")
        }
    }

    val isInitialized: Boolean get() = ctxPtr != 0L

    // ── Conversation management ───────────────────────────────────────────

    /**
     * Reset the conversation (clears KV cache and message history).
     * The model remains loaded.
     */
    suspend fun resetConversation() {
        mutex.withLock {
            if (ctxPtr != 0L) {
                engine.nativeResetContext(ctxPtr)
            }
            history.clear()
            sessionStarted = false
            Log.i(TAG, "Conversation reset")
        }
    }

    // ── Token generation ─────────────────────────────────────────────────

    /**
     * Generate a response to [userMessage], emitting tokens as they arrive.
     *
     * For the FIRST turn, the full conversation (with BOS) is sent to the bridge.
     * For SUBSEQUENT turns, only the new assistant-close + user turn is sent,
     * so the KV cache is extended incrementally — no history re-encoding needed.
     *
     * Emits: [InferenceToken.Piece]+ followed by exactly one [InferenceToken.Done]
     *        or [InferenceToken.Error].
     */
    fun generate(userMessage: String): Flow<InferenceToken> = flow {
        mutex.withLock {
            val ctx   = ctxPtr
            val model = modelPtr
            if (ctx == 0L || model == 0L) {
                emit(InferenceToken.Error("Engine not initialized"))
                return@withLock
            }

            // ── Build the formatted prompt for the bridge ─────────────────
            val formattedPrompt: String
            if (!sessionStarted) {
                // First turn: full history (just this message) + BOS prefix handled
                // by llama_tokenize(add_special=true) inside the bridge.
                formattedPrompt = buildFirstTurnPrompt(userMessage)
                sessionStarted = true
            } else {
                // Subsequent turns: close previous model turn, add new user turn.
                // The bridge will tokenize WITHOUT re-adding BOS (add_special is
                // irrelevant because the context already has the BOS from Turn 1).
                formattedPrompt = buildContinuationPrompt(userMessage)
            }

            Log.d(TAG, "Sending formatted prompt (${formattedPrompt.length} chars)")

            val assistantContent = StringBuilder()
            var generationError: String? = null

            engine.nativeGenerate(ctx, model, formattedPrompt,
                object : TurboQuantEngine.TokenCallback {
                    override fun onToken(token: String) {
                        assistantContent.append(token)
                    }

                    override fun onComplete() {
                        // nothing to do here; handled below
                    }

                    override fun onError(message: String) {
                        generationError = message
                    }
                }
            )

            if (generationError != null) {
                emit(InferenceToken.Error(generationError!!))
                return@withLock
            }

            // Replay token pieces to the Flow (the callback ran synchronously)
            // and record the exchange in history.
            //
            // Note: for true streaming in the UI we emit from the callback.
            // To avoid holding the mutex during emission, we collect the full
            // response and re-emit here. For real-time streaming, call
            // emit() directly inside onToken — but that requires the Flow
            // collector to be re-entrant, which is guaranteed in cold Flows.
            //
            // The approach here is correct for the locking strategy used.
            val response = assistantContent.toString()
            history += ChatMessage(MessageRole.USER, userMessage)
            history += ChatMessage(MessageRole.ASSISTANT, response)

            // Emit the full response piece-by-piece so the UI stream works
            emit(InferenceToken.Piece(response))
            emit(InferenceToken.Done)
        }
    }.flowOn(Dispatchers.IO)

    /**
     * True streaming generation: tokens are emitted immediately as they arrive
     * from the native decode loop, with no buffering delay.
     *
     * Uses [channelFlow] so that [trySend] inside the JNI callback can safely
     * push tokens to the Flow collector without holding a coroutine suspension.
     */
    fun generateStreaming(userMessage: String): Flow<InferenceToken> = channelFlow {
        val ctx   = ctxPtr
        val model = modelPtr
        if (ctx == 0L || model == 0L) {
            send(InferenceToken.Error("Engine not initialized"))
            return@channelFlow
        }

        val formattedPrompt = if (!sessionStarted) {
            sessionStarted = true
            buildFirstTurnPrompt(userMessage)
        } else {
            buildContinuationPrompt(userMessage)
        }

        Log.d(TAG, "Streaming generation (${formattedPrompt.length} chars)")

        val responseBuffer = StringBuilder()
        var errorMsg: String? = null

        // nativeGenerate runs synchronously on the current IO thread.
        // The TokenCallback fires for every token; trySend delivers it
        // to the Flow collector in real time.
        engine.nativeGenerate(ctx, model, formattedPrompt,
            object : TurboQuantEngine.TokenCallback {
                override fun onToken(token: String) {
                    responseBuffer.append(token)
                    trySend(InferenceToken.Piece(token))
                }

                override fun onComplete() { /* handled below */ }
                override fun onError(message: String) { errorMsg = message }
            }
        )

        if (errorMsg != null) {
            send(InferenceToken.Error(errorMsg!!))
            return@channelFlow
        }

        val fullResponse = responseBuffer.toString()
        history += ChatMessage(MessageRole.USER, userMessage)
        history += ChatMessage(MessageRole.ASSISTANT, fullResponse)
        send(InferenceToken.Done)
    }.flowOn(Dispatchers.IO)

    // ── KV cache query (for metrics) ──────────────────────────────────────

    /** Number of token slots currently used in the KV cache. */
    fun kvUsedCells(): Int = if (ctxPtr != 0L) engine.nativeGetKvUsedCells(ctxPtr) else 0

    /** Live MSE from the KV cache quantisation error. */
    fun computeMse(): Float = if (ctxPtr != 0L) engine.nativeComputeMse(ctxPtr) else 0f

    /** Stop the current generation (non-blocking signal). */
    fun stopGeneration() { if (ctxPtr != 0L) engine.nativeStopGeneration(ctxPtr) }

    // ── Cleanup ───────────────────────────────────────────────────────────

    fun release() {
        if (ctxPtr != 0L)   { engine.nativeFreeContext(ctxPtr);  ctxPtr   = 0L }
        if (modelPtr != 0L) { engine.nativeFreeModel(modelPtr);  modelPtr = 0L }
        engine.nativeBackendFree()
        Log.i(TAG, "InferenceManager released")
    }

    // ── Private: Gemma 2B chat template builders ──────────────────────────

    /**
     * First-turn format (BOS is injected by llama_tokenize's add_special flag):
     * ```
     * <start_of_turn>user\n{message}<end_of_turn>\n<start_of_turn>model\n
     * ```
     */
    private fun buildFirstTurnPrompt(userMessage: String): String =
        "<start_of_turn>user\n${userMessage}<end_of_turn>\n<start_of_turn>model\n"

    /**
     * Continuation-turn format (appended to existing KV cache content):
     * ```
     * <end_of_turn>\n<start_of_turn>user\n{message}<end_of_turn>\n<start_of_turn>model\n
     * ```
     */
    private fun buildContinuationPrompt(userMessage: String): String =
        "<end_of_turn>\n<start_of_turn>user\n${userMessage}<end_of_turn>\n<start_of_turn>model\n"
}
